FEC-9707 send user-agent for each http connection
kaltura/playkit-dtg-android pull request #81
Opened 2020-05-25 13:59 UTC by giladna

2020-05-25 19:25 UTC, noamtamim requested changes

2020-05-25 19:25 UTC, noamtamim commented on dtglib/src/main/java/com/kaltura/dtg/Utils.java
> +    static Map headersMap;
- These should be private
- A better name for `headersMap` is `defaultHeaders`

2020-05-25 19:25 UTC, noamtamim commented on dtglib/src/main/java/com/kaltura/dtg/Utils.java
> +    static HttpURLConnection openConnection(Uri uri, Map<String, String> headers) throws IOException {
Since you're **always** passing the shared headers map, you can just remove the parameter and take it directly from the member.

2020-05-25 19:25 UTC, noamtamim commented on dtglib/src/main/java/com/kaltura/dtg/Utils.java
> +    }
Rename to `buildUserAgent` and return `void`, the actual return value is never used. Or better, split to two functions:
`String getUserAgent(Context)` - generate and return the user agent string, without touching the members
`void buildDefaultHeadersMap(Context)` - if the default headers map is null, create it by calling `getUserAgent()`. 

This way the semantics are clearer.

2020-05-26 07:46 UTC, giladna commented on dtglib/src/main/java/com/kaltura/dtg/Utils.java
> +    static HttpURLConnection openConnection(Uri uri, Map<String, String> headers) throws IOException {
done

2020-05-26 07:50 UTC, noamtamim approved these changes

2020-05-26 07:58 UTC, merged